### ISSUE TITLE
How to use? No readme document

### ISSUE THREAD

**Issue by ccbc** [daniel-j/send2ereader#1]
Hey Daniel,
I was using send.djazz.se but it seems that it's not working anymore since a few days. Then, I want to install it on my server, but I don't know how to use the files provided. There is no index.php and no readme to understand the code.

Can you help?
Thanks!

**Comment by daniel-j** [comment]
Hi! Seems like the HDD the project was on ran out of space (not due to uploads, but other things I put on the NAS). I moved it to another drive with more free space.

Yeah I should put a readme... To run it you run `npm install` and then `node index` in the project folder. It will start a web server on port 3001, and you can use nginx or similar to reverse proxy it so you can access it on port 80. I have only tested it on Linux. You also need kepubify and kindlegen installed.

**Comment by ccbc** [comment]
Ok, it seems like I'm going to continue using your own setup instead of creating mine :) Thanks

**Comment by GregHilston** [comment]
For anyone reading this in the future, be sure to use node version 16, and make an empty directory called `uploads`.
